### ISSUE TITLE
[Question] How position the indicator dots?

### ISSUE THREAD

**Issue by stormenergy91** [nixrajput/flutter_carousel_widget#11]
There is a way to change the position on the dots? I need to add more margin as you can see in the image. 
Thanks
![Screenshot 2023-01-26 alle 12 30 54](https://user-images.githubusercontent.com/103607470/214825424-7fdc1051-cfe7-4975-8dfd-5c0644159f7e.png)

**Comment by nixrajput** [comment]
Hi @stormenergy91,

Thanks for using my package.

I am really sorry to inform you that currently it can't be done. But I will add this property in the upcoming update.

As an alternate, you can use a custom indicator in your code and you can place it as per your choice.

Thanks and regards,
@nixrajput

**Comment by nixrajput** [comment]
Hi @stormenergy91 ,

You can now update and set `indicatorMargin` property in `CarouselOptions` as per your choice to position the indicator dots.

Thanks

**Comment by stormenergy91** [comment]
Thanks so much! :)
