### ISSUE TITLE
Overlapping parent

### ISSUE THREAD

**Issue by cloudygeek** [nixrajput/flutter_carousel_widget#2]
Hi

The carousel widget is great and works really well with good options. but the basic constraining to the parent eg a Card, doesn't seem to work?

![image](https://user-images.githubusercontent.com/6059542/153414160-98a55fdf-2c34-4816-8652-721ab9800caa.png)

eg as shown here the carousel is overlapping the edges of the card shown in red lines. 

any ideas?

thanks

**Comment by cloudygeek** [comment]
thanks

return Card( child: FlutterCarousel(
      options: CarouselOptions(
          height: 130.0,
          showIndicator: false,
          slideIndicator: CircularSlideIndicator(),
          enableInfiniteScroll: true,
          reverse: false,
          autoPlay: true,
          autoPlayInterval: Duration(seconds: 5),
          autoPlayAnimationDuration: Duration(milliseconds: 800),
          autoPlayCurve: Curves.fastOutSlowIn,
          enlargeCenterPage: true,
          enlargeStrategy: CenterPageEnlargeStrategy.height),
      items: images.map((media) {
        return Builder(
          builder: (BuildContext context) {
            return Container(
                width: MediaQuery.of(context).size.width,
                margin: EdgeInsets.symmetric(horizontal: 0.0),
                child: CachedNetworkImage(
                  imageUrl: media,
                ));
          },
        );
      }).toList(),
    ));

**Comment by nixrajput** [comment]
Hi @cloudygeek,

Are you trying to show carousel in a single card??
Or you want to show each carousel child in a card??

**Comment by nixrajput** [comment]
```dart
return  Padding(
      padding: const EdgeInsets.all(12.0),
      child:  FlutterCarousel(
      options: CarouselOptions(
          height: 130.0,
          showIndicator: false,
          slideIndicator: CircularSlideIndicator(),
          enableInfiniteScroll: true,
          reverse: false,
          autoPlay: true,
          autoPlayInterval: Duration(seconds: 5),
          autoPlayAnimationDuration: Duration(milliseconds: 800),
          autoPlayCurve: Curves.fastOutSlowIn,
          enlargeCenterPage: true,
          enlargeStrategy: CenterPageEnlargeStrategy.height),
      items: images.map((media) {
        return Builder(
          builder: (BuildContext context) {
            return Card(
               elevation: 6,
                child: CachedNetworkImage(
                  imageUrl: media,
                  width: double.infinty,
                ));
          },
        );
      }).toList(),
    ));
```

I think this will resolve your issue.

**Comment by cloudygeek** [comment]
no that doesn't fix it.

**Comment by nixrajput** [comment]
Hi @cloudygeek 

Please elaorate your issue with more description and if required try to include piece of code as well as screenshot of your output.

Thanks.
