### ISSUE TITLE
[Bug]: [3.7.12] page changed reason is always controller.

### ISSUE THREAD

**Issue by TDuffinNTU** [nixrajput/flutter_carousel_widget#22]
### Contact Details

thomaslukeduffin@hotmail.co.uk

### What happened?

Not sure if this is intentional, but the current impl of the CarouselController class always sets the changed reason to 'controller', regardless of whether a controller is assigned or not, or even if the transition is triggered by autoplay or the user.

I've linked a demo below that I've created that displays and prints the different states. The actions on the top row can be used to quickly toggle autoplay, and whether a controller is assigned to the carousel.

https://pastebin.com/jQr3Sd6P

### Version

^2.0.4

### What devices are you seeing the problem on?

Android

### OS

Android API 33 (emulator~)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by nixrajput** [comment]
Hi @TDuffinNTU,

Thank you for raising the issue.

I will look into this issue and will try to fix it in the next update.
If you found any solution to this issue, you can make a pull request for the same.

Regards,
Nikhil
