### ISSUE TITLE
[Feature Request]:  Maximum height value

### ISSUE THREAD

**Issue by bugrevealingbme** [nixrajput/flutter_carousel_widget#25]
### Contact Details

strixbme@gmail.com

### Is your feature request related to a problem? Please describe.

I am using Expandable Carousel. I want to set the maximum height. Thanks

### Describe the solution you'd like

Maxheight:

### Describe alternatives you've considered

I think easy solution

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 7snalbar** [comment]
I'm not sure if wrapping the Expanded widgets inside a ConstrainedBox will work since Expanded calculates it dynamically, would you be able to share a sample of code?

**Comment by bugrevealingbme** [comment]
ConstrainedBox worked. Thanks
