### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mjablecnik** [nixrajput/flutter_carousel_widget#27]
### What happened?

Hello, why do you use the GNU/GPL license for your package? The conditions of this license require me to disclose the source code under the same license, but I'm unable to do so, which means I cannot use this package.

Why don't you consider using the MIT license, which is better suited for libraries? All Flutter packages are distributed under the MIT license. The GNU/GPL license is more suitable for applications and programs that you want to keep open, but not for packages that can be used by any application.

The MIT license allows for copying your package's code under the same license, without the requirement to disclose the entire application that wants to use this package.

### Version

2.0.4

### What devices are you seeing the problem on?

Android, iPhone, Windows, Mac, Linux

### OS

any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nixrajput** [comment]
Hi @mjablecnik,

Thank you for your suggestion. I will definitely look into it and consider your concern.

Regards,
Nikhil

**Comment by wcfv** [comment]
Agreed.  Glad I saw this, I thought every popular library in pub.dev was MIT.  Now I have to swap this out AGAIN with some WORSE carousel.  What a shame.  Great carousel.  Keep up the good work, but I cannot use it either.

> The GPL (General Public License) is indeed a "copyleft" license, which means that any derivative work must be distributed under the same license terms. This includes linking or integrating GPL-licensed code into your own project.
> 
> If your commercial application uses a library that is under the GPL-3.0 license, and if you distribute your application, the terms of the GPL require that your entire application be made available under the GPL as well. This means you would need to provide the source code of your application to anyone who receives a copy of your application, under the same GPL-3.0 license terms. 
> 
> There is some ongoing debate in the software industry as to whether simply linking to a GPL-licensed library constitutes creating a derivative work, but the conservative and safer interpretation is to treat it as such.
> 
> In the end, the specifics can depend on how the library is used, and how it is linked or integrated with your application. To be safe, it's generally a good idea to avoid using GPL-licensed libraries in commercial applications that you don't intend to open source, unless you have received explicit permission from the library's authors to use it under different terms, or you have a solid understanding of the license terms and how they apply to your use case. 

Not worth the legal fees we'll rack up trying to figure out if we can use this without revealing all of our source code, we'll just have to pick a different library.  Or... you could just change this to a more permissive license, such as the MIT License, Apache 2.0 License, or the BSD license ;)
