### ISSUE TITLE
[Bug]: Indicator remains half-filled when padEnds: false

### ISSUE THREAD

**Issue by RafiaChy** [nixrajput/flutter_carousel_widget#28]
### What happened?

Hi guys , the indicator gets stuck in the middle when I set padEnd to false. And it needs to false to make the carousel occupy the entire screen.                                           
          ExpandableCarousel(
          options: CarouselOptions(
            showIndicator: true,
            padEnds: false,
            viewportFraction: athletes.length > 1 ? 0.8 : 0.9,
            floatingIndicator: false,
            slideIndicator: CircularSlideIndicator(
                //padding: const EdgeInsets.only(top: 100),
                currentIndicatorColor: ColorManager.primary),
          ),
![picture](https://github.com/nixrajput/flutter_carousel_widget/assets/55042866/87d9fd6c-109c-44a2-8511-edf1b22aa7f5)

### Version

2.0.1

### What devices are you seeing the problem on?

Android

### OS

Android 12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nixrajput** [comment]
Hi @RafiaChy,

Thank you for using the package and raising this issue.

I will look into this issue and hope to fix it in the next update.

Regards,
Nikhil(@nixrajput )
