### ISSUE TITLE
Feature: Tap indicator change slider

### ISSUE THREAD

**Issue by moinkhan780** [nixrajput/flutter_carousel_widget#31]
Feature: Tap indicator change slider

**Comment by nixrajput** [comment]
Hi @moinkhan780,

Please explain your feature in detail.

Thanks,
Nikhil

**Comment by moinkhan780** [comment]
> Hi @moinkhan780,
> 
> Please explain your feature in detail.
> 
> Thanks, Nikhil

When we click on specific indicator it should navigate to that index slider.

**Comment by nixrajput** [comment]
Hi @moinkhan780,

For that purpose, you can use a custom indicator in the carousel.

Thanks and regards,
Nikhil
