### ISSUE TITLE
Difference vs. flutter_carousel_slider

### ISSUE THREAD

**Issue by Colton127** [nixrajput/flutter_carousel_widget#4]
What is the difference between this package and https://github.com/serenader2014/flutter_carousel_slider? The code appears nearly identical.

**Comment by nixrajput** [comment]
hi @Colton127 ,
Yeah, you are right. The code is nearly indentical and I inherited the pretty much code from that package.
But previous version of `flutter_carousel_slider` package had some bugs and I have fixed these bugs in my package.
Apart from the bugs, I have also added pre-built indicator support in this package.
I am also looking to add some new features in the package, if you have some idea or requirements, you can discuss with me.
You are also welcome to contribute in the package if you are interested.
Thanks.
@nixrajput

**Comment by under3415** [comment]
They are looking for an owner, just saying ;-)
https://github.com/serenader2014/flutter_carousel_slider/issues/289
