### ISSUE TITLE
[Bug]: Next Flutter add a Carousel Widget

### ISSUE THREAD

**Issue by patou** [nixrajput/flutter_carousel_widget#42]
### What happened?

Flutter works to add a new Carousel widget, and it's integrated in the main channel.

https://github.com/flutter/flutter/pull/148094

When compile our application with the flutter main channel, the compile didn't works because two CarouselController now exist, for our code we can updated with : 
```
import 'package:flutter/material.dart' hide CarouselController;
```

But there are errors in this lib flutter_carousel_widget.

There are 4 files with erros : 
- /lib/src/helpers/flutter_carousel_options.dart
- /lib/src/helpers/flutter_carousel_controller.dart
- /lib/src/_flutter_carousel_widget.dart
- /lib/src/_expendable_carousel_widget.dart

### Version

2,2,

### What devices are you seeing the problem on?

iPhone

### OS

Flutter chanel main 3.23.0-13.0.pre.212

### Relevant log output

```shell
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/flutter_carousel_widget-2.2.0/lib/src/helpers/flutter_carousel_options.dart:88:9: Error: 'CarouselController' is imported from both 'package:flutter/src/material/carousel.dart' and 'package:flutter_carousel_widget/src/helpers/flutter_carousel_controller.dart'.

Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/flutter_carousel_widget-2.2.0/lib/src/_flutter_carousel_widget.dart:149:13: Error: 'CarouselController' is imported from both 'package:flutter/src/material/carousel.dart' and 'package:flutter_carousel_widget/src/helpers/flutter_carousel_controller.dart'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by InstantlyMoist** [comment]
Opened a PR for this, hopefully gets accepted soon :D

**Comment by nixrajput** [comment]
Thank you for the PR.

I will accept it after review and then release an update ASAP.
