### ISSUE TITLE
[Feature Request]: Indicator Halo

### ISSUE THREAD

**Issue by ProV1X** [nixrajput/flutter_carousel_widget#44]
### Is your feature request related to a problem? Please describe.

I love the convenience and functionality of the prebuilt indicators. However, I often find that the indicators can blend in with the background image or content they're layered on top of.

To improve the visual prominence and usability of prebuilt indicators, I propose adding an optional "halo" decoration. This halo would be a customizable BoxDecoration that surrounds the indicator, making it stand out more clearly.

### Describe the solution you'd like

<img src="https://github.com/nixrajput/flutter_carousel_widget/assets/124012838/f82d8083-da7c-4d6f-897b-776cd7bc6cbd" height="400" />

<img src="https://github.com/nixrajput/flutter_carousel_widget/assets/124012838/dacd426a-991a-4835-b73c-8d20bc3ed4ab" height="400" />

### Describe alternatives you've considered

I used a custom indicator. It felt like a lot of added code for a relatively low-cost change to prebuilt indicators.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nixrajput** [comment]
Hi @ProV1X,

Thank you for your pull request. I have merged and released the update.

Could you please update the README to include a description of your feature, following the format of previous feature descriptions?

Additionally, please add a demo in the example section as a new screen.

Regards,  
Nikhil

**Comment by nixrajput** [comment]
Thanks @ProV1X !!!
