### ISSUE TITLE
[Bug]: Height of last item in ExpandableCarousel does not adapt

### ISSUE THREAD

**Issue by aferret0** [nixrajput/flutter_carousel_widget#48]
### What happened?

We are using ExpandableCarousel in our projet, we have 3 items and when the last item has more text than the other it should be bigger and the slide indicator should be below it.

Exemple with 3rd item bigger than others :
Video :  https://github.com/user-attachments/assets/6b6df72d-f754-4056-8f1f-74119478cd98
Screenshot :  ![image](https://github.com/user-attachments/assets/b09d1e53-5e72-423d-9a09-72283fb02f68)

As we can see, slide indicator is above the 3rd item which had not adapted his height.

Exemple with 2nd item bigger than others :
Video : https://github.com/user-attachments/assets/5aa2cf1a-7148-458d-bfca-8ab75d14b999
Screenshot : ![image](https://github.com/user-attachments/assets/7ecb519c-7c23-494e-abeb-09723135a685)

As we can see 2nd item has increased his size to match his content but 3rd didn't changed and keep the same size

### Version

2.2.0

### What devices are you seeing the problem on?

Android, iPhone

### OS

Android 14, iOS 17.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aferret0** [comment]
any updates ?

**Comment by nixrajput** [comment]
Can you help me providing with what `CarouselOptions` properties you are using for this output? Will fix this issue if found in the package. Currently, it is working fine on my side.
