### ISSUE TITLE
Suggest an idea for this project

### ISSUE THREAD

**Issue by nixrajput** [nixrajput/flutter_carousel_widget#5]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rafaellop** [comment]
Great package. Thanks! I'd like to suggest autopause feature when the carousel is out of view. Use case is a design where expandable carousel is used which cause the widgets below carousel are moving up/down depending on the carousel page currently displayed. Would be great if this unwanted effect could be stopped when the carousel is out of view (e.g. scrolled up/down).

**Comment by wisnhusurya** [comment]
When autoplay is true, and scroll in last index, Can you make from last index directly to first index instead of last index -> (some index) to -> first index?
