### ISSUE TITLE
[Bug]: 2.3.0 is not backwards compatible with 2.2.0

### ISSUE THREAD

**Issue by aferret0** [nixrajput/flutter_carousel_widget#51]
### What happened?

In 2.2.0 we were able to pass CarouselOptions as options to ExpandableCarousel

In 2.3.0 we have to pass ExpandableCarouselOptions as options to ExpandableCarousel

If it's not backwards compatible, it should have been 3.0.0 ?

Another solution could be to accept CarouselOptions && ExpandableCarouselOptions as options to ExpandableCarousel or ExpandableCarouselOptions should inherit from CarouselOptions ?

### Version

2.3.0

### What devices are you seeing the problem on?

Android, iPhone

### OS

Android, iOS

### Relevant log output

```shell
error • The argument type 'CarouselOptions' can't be assigned to the parameter type 'ExpandableCarouselOptions'.  • lib/molecules/maif_carousel.dart:93:16 • argument_type_not_assignable
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nixrajput** [comment]
Hi @aferret0,

Thank you for using the package and for pointing out the issue.

I will address this problem and ensure backward compatibility.

However, due to personal commitments, I'm currently unable to dedicate time to work on this package. If you’re able to fix the issue, please feel free to submit a PR. This would greatly benefit the users, and I will review and merge the PR as soon as possible.

Best regards,
Nikhil

**Comment by Gustl22** [comment]
As the package is released already, it would be again breaking, when upgrading to 2.4.0. The best approach would be to release the current state as 3.0.0 and remove the last release (if possible).

**Comment by nixrajput** [comment]
The next release will be a major release (v3.0.0).

**Comment by aferret0** [comment]
I'm back from holidays, I can now start to do some work and submit a PR

**Comment by nixrajput** [comment]
Hi @aferret0,

Could you please work on the CarouselOptions issue (#51) to ensure backward compatibility within the package? Your contribution would greatly help us expedite the next update.

In the meantime, I have resolved issue #37 and am currently adding some test cases to improve the package. Once issue #52 is also addressed, I will release the next update (v3.0.0) as soon as possible.

If you're available to work on issue #51, please confirm here.

Thank you for your help.

Best regards,
Nikhil

**Comment by aferret0** [comment]
I will work on it after my work, this issue should be updated within the next 24 hours

**Comment by nixrajput** [comment]
Great!!!
