### ISSUE TITLE
[Bug]: Demo app is not loading

### ISSUE THREAD

**Issue by aytunch** [nixrajput/flutter_carousel_widget#54]
### What happened?

https://nixrajput.github.io/flutter_carousel_widget
is not loading

### Version

3.0.1

### What devices are you seeing the problem on?

iPhone

### OS

18

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nixrajput** [comment]
Hi @aytunch,

I’ve checked the demo at [this URL](https://nixrajput.github.io/flutter_carousel_widget), and everything seems to be working fine. Please try again and review the demo app. I'll close this issue for now, but feel free to reopen it if the problem persists.

Thanks and best regards,
Nikhil
