### ISSUE TITLE
[Bug]: `onScrolled` not being fired

### ISSUE THREAD

**Issue by jorgelrj** [nixrajput/flutter_carousel_widget#55]
### What happened?

The `onScrolled` callback is not firing anymore after the recent updates

```
child: NotificationListener<ScrollEndNotification>(
        onNotification: (dynamic notification) {
          if (widget.options.onScrolled != null &&
              notification is ScrollUpdateNotification) {
            widget.options.onScrolled!(_carouselState!.pageController!.page);
          }
          return false;
        },
        child: wrapper, // The child widget (carousel)
      ),
```

The notification listener is filtering by `ScrollEndNotification` notifications only

### Version

^3.0.1

### What devices are you seeing the problem on?

Android, iPhone, Windows, Mac, Linux

### OS

all

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nixrajput** [comment]
Hi @jorgelrj,

Thank you for reporting this! I'll look into the issue and verify if it's a bug in the package. If it is, I'll make sure to include a fix in the next update.

In the meantime, it seems the `NotificationListener` is filtering only for `ScrollEndNotification` events. You could try modifying the listener to capture other notifications, such as `ScrollUpdateNotification`, to see if that resolves the problem temporarily.

I'll keep you updated on the progress.

Best regards,
Nikhil

**Comment by nixrajput** [comment]
Hi @jorgelrj,

This issue has been fixed in the latest release. Please update to the latest version and check if the issue has been resolved on your end.

If everything is working fine, kindly close this issue. If you encounter any further problems, feel free to reopen the issue or create a new one.

Thank you for your patience and support!

Best regards,
Nikhil
