### ISSUE TITLE
bug show indicator

### ISSUE THREAD

**Issue by rymesaint** [nixrajput/flutter_carousel_widget#7]
trying to hide the indicator using **showIndicator: false** but the indicator still showing up

**Comment by nixrajput** [comment]
Can you provide your code snippet and output screenshot?

Also, mention which version of the package you are using.

**Comment by rymesaint** [comment]
```dart
FlutterCarousel.builder(
        options: CarouselOptions(
          aspectRatio: 16 / 9,
          autoPlay: false,
          enableInfiniteScroll: false,
          height: Get.height,
          initialPage: controller.initialPage.value,
          floatingIndicator: false,
          scrollDirection: Axis.vertical,
          showIndicator: false,
          pageSnapping: false,
          enlargeCenterPage: true,
          enlargeStrategy: CenterPageEnlargeStrategy.height,
          slideIndicator: const CircularSlideIndicator(
            itemSpacing: 0,
            indicatorBackgroundColor: Colors.transparent,
            currentIndicatorColor: Colors.transparent,
            indicatorBorderColor: Colors.transparent,
          ),
        ),
        itemBuilder: (context, index, realIndex) {
          final image = controller.comic.images![realIndex];
          return Image.asset(image, width: Get.width);
        },
        itemCount: controller.comic.images?.length ?? 0,
      ),
```

package version : 

flutter_carousel_widget: ^1.2.1

**Comment by nixrajput** [comment]
I don't find any issue with your code, so can you share some screenshots of your output screens?

You can see in the package demo that the `showIndicator` property is working fine.

**Comment by bradintheusa** [comment]
For me it shows up on the first tab

![image](https://user-images.githubusercontent.com/1160356/202353130-ca57205d-40bd-4be4-828b-56a71c7bff2c.png)

but then once I navigate it never shows again
![image](https://user-images.githubusercontent.com/1160356/202353191-88b7f170-c244-40b4-abd2-5478eb430908.png)

```dart

                  FlutterCarousel(
                    carouselController: _controller,
                    options: CarouselOptions(
                        showIndicator: true,
                        autoPlay: false,
                        slideIndicator: CircularSlideIndicator(
                            currentIndicatorColor: AppColors.buttonGreen),
                        onPageChanged: (index, reason) {
                          setState(() {
                            _current = index;
                          });
                        }),
                    items: tabList.map((i) {
                      return Builder(
                        builder: (BuildContext context) {
                          return ProjectionsDay(
                              data: snapshot.data!.;
                        },
                      );
                    }).toList(),
                  ),


```

**Comment by bradintheusa** [comment]
You can see it slide out but it looks like it never slides into the next one

![image](https://user-images.githubusercontent.com/1160356/202475344-c91b8b06-ea88-4238-8376-15522c70e446.png)

**Comment by nixrajput** [comment]
Hi @bradintheusa,

Can you please share the full code implementation and which version you are using?

Thanks

**Comment by bradintheusa** [comment]
It's the latest version. Let me see if I can extract it into a small sample.

**Comment by nixrajput** [comment]
You can share the repo link if you push your code in a GitHub repo.

**Comment by bradintheusa** [comment]
https://github.com/bradintheusa/flutter_carousel_widget

**Comment by nixrajput** [comment]
The problem is when you are using a custom `Carousel Controller`, you have to use a custom slide indicator to work efficiently.

I will fix this bug in the next update.
Thank you for raising this issue.

**Comment by bradintheusa** [comment]
Thanks. I put the fix in Github for others to see.

The fix is to set `showIndicator: false`, and add a row manually at the bottom
