### ISSUE TITLE
Add option for dynamic height based on the child's height

### ISSUE THREAD

**Issue by alyyasser** [nixrajput/flutter_carousel_widget#8]
Is it possible to add an option for dynamic height? in my use case, the children widget's height isn't fixed, there's possibility that one children's height isn't the same with the other children's height.

![image](https://user-images.githubusercontent.com/16476111/206661872-22ae9cdf-c46b-414e-afdd-9542c0e37596.png)
within that card, there's a dynamically loaded widget, sometimes loaded, sometimes not.
because the current implementation forced children's height to be the same as the height set on the option, it makes a blank space within the card. would be great if the carousel doesn't force the height at least. and even better if there's option for dynamic height.

**Comment by nixrajput** [comment]
Hi @alyyasser,

For your kind information, I have published an expandable widget carousel support in the latest update.

This carousel widget will accommodate its height according to the child widget.

Hope this will help you regarding your concern.

Your response will be highly appreciated.

Thanks
Nikhil Rajput
