### ISSUE TITLE
[Question] Remove Center from each child

### ISSUE THREAD

**Issue by stormenergy91** [nixrajput/flutter_carousel_widget#9]
The plugin is forcing a center widget in each of its elements, constraining the application of this plugin.

E.g If i want the carousel to have the image at left of the screen it would be almost impossible because of this Center widget without using some obscure hacky stuff ;)

There is some way to don't force this behavior in the carousel?

I want to have this effect

![immagine](https://user-images.githubusercontent.com/103607470/212100563-3b5e91ac-d289-4b10-9e40-682a0b793663.png)

Edit:
I tried to use the `disableCenter: true` option but it doesn't work.

**Comment by nixrajput** [comment]
Hi @stormenergy91,

Thank you for using this package.

I will look into this issue and will fix it in the next update.

Thanks again for raising the issue.

**Comment by stormenergy91** [comment]
Thanks @nixrajput, is a great plugin. If you need more info ora some testing I'm here!

**Comment by nixrajput** [comment]
I will definitely reach out to you if required.

Can I ask you how to make an image from the screenshots like the image you shared above?

**Comment by nixrajput** [comment]
Hi @stormenergy91,

Can you please share some code snippets for testing the changes you want in the package?

**Comment by nixrajput** [comment]
Hi @stormenergy91,

I checked and tested the code and I found that no additional change requires in the code for this issue.

In your case, you can use `padEnds` property to `false`.

```dart
CarouselOptions(
  viewportFraction: 0.70,
  height: 280.0,
  showIndicator: false,
  padEnds: false,
  enableInfiniteScroll: false,
  slideIndicator: CircularSlideIndicator(),
),
```
Thanks

**Comment by stormenergy91** [comment]
Thanks so much! :)
